# Generated by Django 5.1.2 on 2024-11-02 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contenido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200)),
                ("descripcion", models.TextField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[("pelicula", "Película"), ("serie", "Serie")],
                        default="pelicula",
                        max_length=10,
                    ),
                ),
                ("fecha_publicacion", models.DateField()),
            ],
            options={
                "ordering": ["-fecha_publicacion"],
            },
        ),
    ]
