# Generated by Django 5.1.2 on 2024-11-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenido", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contenido",
            name="image_card",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
