# Generated by Django 5.1.2 on 2024-11-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenido", "0003_contenido_actores_contenido_calificacion_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contenido",
            name="genero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accion", "Acción"),
                    ("comedia", "Comedia"),
                    ("drama", "Drama"),
                    ("terror", "Terror"),
                    ("romance", "Romance"),
                    ("ciencia_ficcion", "Ciencia Ficción"),
                    ("fantasia", "Fantasía"),
                    ("misterio", "Misterio"),
                    ("suspenso", "Suspenso"),
                    ("animacion", "Animación"),
                    ("documental", "Documental"),
                    ("biografia", "Biografía"),
                    ("musical", "Musical"),
                    ("historico", "Histórico"),
                    ("aventura", "Aventura"),
                    ("guerra", "Guerra"),
                    ("crimen", "Crimen"),
                    ("familiar", "Familiar"),
                    ("anime", "Anime"),
                ],
                max_length=100,
                null=True,
            ),
        ),
    ]
