# Generated by Django 5.1.2 on 2024-11-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenido", "0005_remove_contenido_image_card_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contenido",
            options={},
        ),
        migrations.AddField(
            model_name="contenido",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
    ]
