# Generated by Django 5.1.2 on 2024-11-12 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenido", "0006_alter_contenido_options_contenido_is_featured"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contenido",
            old_name="descripcion",
            new_name="sinopsis",
        ),
        migrations.RemoveField(
            model_name="contenido",
            name="capitulos_totales",
        ),
        migrations.RemoveField(
            model_name="contenido",
            name="fecha_publicacion",
        ),
        migrations.RemoveField(
            model_name="contenido",
            name="is_featured",
        ),
        migrations.RemoveField(
            model_name="contenido",
            name="temporadas_totales",
        ),
        migrations.RemoveField(
            model_name="contenido",
            name="video",
        ),
        migrations.AddField(
            model_name="contenido",
            name="año",
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
