# Generated by Django 5.1.3 on 2024-11-17 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MiFlixApp", "0002_alter_pelicula_id_alter_serie_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="image_cover",
            field=models.ImageField(blank=True, null=True, upload_to="movie_images/"),
        ),
        migrations.AlterField(
            model_name="serie",
            name="image_cover",
            field=models.ImageField(blank=True, null=True, upload_to="series_images/"),
        ),
    ]
