# Generated by Django 5.1.3 on 2024-12-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MiFlixApp", "0004_alter_pelicula_options_alter_serie_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="calificacion_usuario",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="serie",
            name="calificacion_usuario",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
