# Generated by Django 5.1.2 on 2024-11-03 09:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenido", "0001_initial"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioContenido",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("favorito", models.BooleanField(default=False)),
                ("visto", models.BooleanField(default=False)),
                (
                    "contenido",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenido.contenido",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("usuario", "contenido")},
            },
        ),
        migrations.DeleteModel(
            name="Contenido",
        ),
    ]
