# Generated by Django 5.1.3 on 2024-11-17 17:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MiFlixApp", "0003_alter_pelicula_image_cover_alter_serie_image_cover"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuariocontenido",
            name="favorito",
        ),
        migrations.RemoveField(
            model_name="usuariocontenido",
            name="ver_mas_tarde",
        ),
        migrations.RemoveField(
            model_name="usuariocontenido",
            name="visto",
        ),
        migrations.AddField(
            model_name="usuariocontenido",
            name="fecha_agregado",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="usuariocontenido",
            name="pelicula",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios_pelicula",
                to="MiFlixApp.pelicula",
            ),
        ),
        migrations.AlterField(
            model_name="usuariocontenido",
            name="serie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios_serie",
                to="MiFlixApp.serie",
            ),
        ),
        migrations.AlterField(
            model_name="usuariocontenido",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mi_lista",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
