# Generated by Django 5.1.3 on 2024-11-18 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_remove_usuariocontenido_favorito_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariocontenido",
            name="favorito",
            field=models.BooleanField(default=False),
        ),
    ]
