# Generated by Django 5.1.2 on 2024-11-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_usuariocontenido_ver_mas_tarde"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="es_administrador",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="es_cliente",
        ),
        migrations.AddField(
            model_name="usuario",
            name="role",
            field=models.CharField(
                choices=[("ADMIN", "Administrador"), ("CLIENT", "Cliente")],
                default="CLIENT",
                max_length=10,
            ),
        ),
    ]
