# Generated by Django 5.1.3 on 2024-11-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0003_usuariocontenido_favorito"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuariocontenido",
            name="visto",
            field=models.BooleanField(default=False),
        ),
    ]
