# Generated by Django 5.1.3 on 2024-12-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0010_usuarioserie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuariocontenido",
            name="calificacion",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
