# Generated by Django 5.1.2 on 2024-10-31 08:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uu_id", models.UUIDField(default=uuid.uuid4)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("action", "Acción"),
                            ("comedy", "Comedia"),
                            ("drama", "Drama"),
                            ("horror", "Terror"),
                            ("romance", "Romance"),
                            ("science_fiction", "Ciencia Ficción"),
                            ("fantasy", "Fantasía"),
                        ],
                        max_length=100,
                    ),
                ),
                ("length", models.PositiveIntegerField()),
                ("image_card", models.ImageField(upload_to="movie_images/")),
                ("image_cover", models.ImageField(upload_to="movie_images/")),
                ("video", models.FileField(upload_to="movie_videos/")),
                ("movie_views", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="MovieList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ClonFlixApp.movie",
                    ),
                ),
            ],
        ),
    ]
