# Generated by Django 5.1.3 on 2024-11-17 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClonFlixApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="serie",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
