# Generated by Django 5.1.2 on 2024-10-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClonFlixApp", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="tipo",
            field=models.CharField(
                choices=[("pelicula", "Película"), ("serie", "Serie")],
                default="pelicula",
                max_length=10,
            ),
        ),
    ]
