# Generated by Django 5.1.2 on 2024-10-31 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClonFlixApp", "0003_movie_tipo"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="capitulos_totales",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="temporadas_totales",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
