# Generated by Django 5.1.3 on 2024-11-19 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ClonFlixApp", "0003_alter_pelicula_image_cover_alter_serie_image_cover"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="pelicula",
            options={"verbose_name": "Película", "verbose_name_plural": "Películas"},
        ),
        migrations.AlterModelOptions(
            name="serie",
            options={"verbose_name": "Serie", "verbose_name_plural": "Series"},
        ),
    ]
