# Generated by Django 5.1.2 on 2024-11-02 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ClonFlixApp", "0004_movie_capitulos_totales_movie_temporadas_totales"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="uu_id",
        ),
    ]
