# Generated by Django 5.1.2 on 2024-11-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClonFlixApp", "0005_remove_movie_uu_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.CharField(default="Desconocido", max_length=500),
        ),
        migrations.AddField(
            model_name="movie",
            name="director",
            field=models.CharField(default="Desconocido", max_length=255),
        ),
        migrations.AddField(
            model_name="movie",
            name="rating",
            field=models.DecimalField(
                blank=True, decimal_places=1, max_digits=3, null=True
            ),
        ),
    ]
