# Generated by Django 5.1.3 on 2024-12-18 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClonFlixApp", "0005_alter_pelicula_calificacion_usuario_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="calificacion_usuario",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
