# Generated by Django 5.1.3 on 2024-12-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ClonFlixApp", "0006_alter_pelicula_calificacion_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pelicula",
            name="calificacion_usuario",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
