# Generated by Django 5.1.2 on 2024-11-10 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ClonFlixApp", "0007_alter_movie_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movielist",
            name="movie",
        ),
        migrations.RemoveField(
            model_name="movielist",
            name="owner_user",
        ),
        migrations.DeleteModel(
            name="Movie",
        ),
        migrations.DeleteModel(
            name="MovieList",
        ),
    ]
