# Generated by Django 5.1.2 on 2024-11-10 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "ClonFlixApp",
            "0008_remove_movielist_movie_remove_movielist_owner_user_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("release_date", models.DateField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("accion", "Acción"),
                            ("comedia", "Comedia"),
                            ("drama", "Drama"),
                            ("terror", "Terror"),
                            ("romance", "Romance"),
                            ("ciencia_ficcion", "Ciencia Ficción"),
                            ("fantasia", "Fantasía"),
                            ("misterio", "Misterio"),
                            ("suspenso", "Suspenso"),
                            ("animacion", "Animación"),
                            ("documental", "Documental"),
                            ("biografia", "Biografía"),
                            ("musical", "Musical"),
                            ("historico", "Histórico"),
                            ("aventura", "Aventura"),
                            ("guerra", "Guerra"),
                            ("crimen", "Crimen"),
                            ("familiar", "Familiar"),
                            ("anime", "Anime"),
                        ],
                        max_length=100,
                    ),
                ),
                ("length", models.PositiveIntegerField()),
                ("image_card", models.ImageField(upload_to="movie_images/")),
                ("image_cover", models.ImageField(upload_to="movie_images/")),
                ("video", models.FileField(upload_to="movie_videos/")),
                ("movie_views", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                (
                    "tipo",
                    models.CharField(
                        choices=[("pelicula", "Película"), ("serie", "Serie")],
                        default="pelicula",
                        max_length=10,
                    ),
                ),
                (
                    "temporadas_totales",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "capitulos_totales",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("director", models.CharField(default="Desconocido", max_length=255)),
                ("actors", models.CharField(default="Desconocido", max_length=500)),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=1, max_digits=3, null=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovieList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ClonFlixApp.movie",
                    ),
                ),
                (
                    "owner_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
